# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f8963def49ed2a0061c6afbbb23487f7b96488e71c183557c645341e97bdbb3505d2e83e69f08e074549d08cfbcae74a8ce502b80a30d630ca956be8f267f05

test:
  secret_key_base: 53dc3f9937fd4f827df128bb8bfee5c7fecf0995a0fa9017a96bf38ccaa67559521f186833b41e87cea06321ab2553aeb9ac42dc7f415f7bc24ef41b48ff6a46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
